defaults: &defaults
  working_directory: ~/circleci-python
  docker:
      - image: circleci/python:3.6.1

version: 2
jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: . 
          paths: .

  python_dependencies:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
          - pv-deps-{{ checksum "requirements.txt" }}
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: pv-deps-{{ checksum "requirements.txt" }}

  static_dependencies:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: 
          name: run static analysis
          command: |
            . venv/bin/activate
            flake8 test_fizzbuzz.py

  unit_tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python test_fizzbuzz.py

workflows:
  version: 2
  circleci_python_workshop_pipeline:
    jobs:
      - checkout_code
      - python_dependencies:
          requires:
            - checkout_code
      - static_dependencies:
          requires:
            - python_dependencies
      - unit_tests:
          requires:
            - python_dependencies
